### ISSUE TITLE
Could not find/found font

### ISSUE THREAD

**Issue by pr1m0rdial** [addrmwn/quotemaker#1]
Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1118

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1039

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1118

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1014

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1062

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 952

Warning: imagefttext(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 996

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1014

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 1062

Warning: imageftbbox(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 952

Warning: imagefttext(): Could not find/open font in E:\xampp\htdocs\quotemaker-master\config\function.php on line 996

**Comment by addrmwn** [comment]
maybe you should try on hosting not localhost
